name: Automated Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17'
      - name: Setup Selenium Server
        run: docker pull selenium/standalone-chrome:latest
      - name: Start Selenium Server
        run: docker run --net=host -d -p 4444:4444 --name selenium-server selenium/standalone-chrome
      # - name: Download selenoid (Selenium server)
      #   run: curl -s https://aerokube.com/cm/bash | bash
      # - name: Give permission to selenoid (Selenium server)
      #   run: chmod +x ./cm
      # - name: Start selenoid (Selenium server)
      #   run: ./cm selenoid start --browsers 'chrome;safari' --last-versions 1
      - name: Install dependencies
        run: npm ci
      - name: Create Service Account key for Firebase
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > gcloud.json
      - name: Run tests with chrome
        run: |
          SELENIUM_REMOTE_URL="http://localhost:4444/wd/hub" SELENIUM_BROWSER=chrome npm test
        env:
          TOKEN: ${{ secrets.TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: "gcloud.json"
          MERCHANTID: ${{ secrets.MERCHANTID }}
          MERCHANTPUBLIC: ${{ secrets.MERCHANTPUBLIC }}
          MERCHANTPRIVATE: ${{ secrets.MERCHANTPRIVATE }}
      # - name: Stop selenoid (Selenium server)
      #   run: ./cm selenoid stop